import { GitHubRepo } from "./types"

export const getRepositoriesResponse = new Promise<{ data: (Record<string, any> & GitHubRepo<Record<string, any>>)[] }>((resolve) => setTimeout(() => {
    return resolve({
        "data": [
            {
                "id": 945060412,
                "node_id": "R_kgDOOFR6PA",
                "name": "fe-react-portfolio",
                "full_name": "5h1ngy/fe-react-portfolio",
                "private": false,
                "owner": {
                    "login": "5h1ngy",
                    "id": 109795840,
                    "node_id": "U_kgDOBotaAA",
                    "avatar_url": "https://avatars.githubusercontent.com/u/109795840?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/5h1ngy",
                    "html_url": "https://github.com/5h1ngy",
                    "followers_url": "https://api.github.com/users/5h1ngy/followers",
                    "following_url": "https://api.github.com/users/5h1ngy/following{/other_user}",
                    "gists_url": "https://api.github.com/users/5h1ngy/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/5h1ngy/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/5h1ngy/subscriptions",
                    "organizations_url": "https://api.github.com/users/5h1ngy/orgs",
                    "repos_url": "https://api.github.com/users/5h1ngy/repos",
                    "events_url": "https://api.github.com/users/5h1ngy/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/5h1ngy/received_events",
                    "type": "User",
                    "user_view_type": "public",
                    "site_admin": false
                },
                "html_url": "https://github.com/5h1ngy/fe-react-portfolio",
                "description": null,
                "fork": false,
                "url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio",
                "forks_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/forks",
                "keys_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/teams",
                "hooks_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/hooks",
                "issue_events_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/issues/events{/number}",
                "events_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/events",
                "assignees_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/assignees{/user}",
                "branches_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/branches{/branch}",
                "tags_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/tags",
                "blobs_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/languages",
                "stargazers_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/stargazers",
                "contributors_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/contributors",
                "subscribers_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/subscribers",
                "subscription_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/subscription",
                "commits_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/contents/{+path}",
                "compare_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/merges",
                "archive_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/downloads",
                "issues_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/issues{/number}",
                "pulls_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/labels{/name}",
                "releases_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/releases{/id}",
                "deployments_url": "https://api.github.com/repos/5h1ngy/fe-react-portfolio/deployments",
                "created_at": "2025-03-08T15:10:55Z",
                "updated_at": "2025-03-08T15:10:56Z",
                "pushed_at": "2025-03-08T15:10:56Z",
                "git_url": "git://github.com/5h1ngy/fe-react-portfolio.git",
                "ssh_url": "git@github.com:5h1ngy/fe-react-portfolio.git",
                "clone_url": "https://github.com/5h1ngy/fe-react-portfolio.git",
                "svn_url": "https://github.com/5h1ngy/fe-react-portfolio",
                "homepage": null,
                "size": 0,
                "stargazers_count": 0,
                "watchers_count": 0,
                "language": null,
                "has_issues": true,
                "has_projects": true,
                "has_downloads": true,
                "has_wiki": true,
                "has_pages": false,
                "has_discussions": false,
                "forks_count": 0,
                "mirror_url": null,
                "archived": false,
                "disabled": false,
                "open_issues_count": 0,
                "license": null,
                "allow_forking": true,
                "is_template": false,
                "web_commit_signoff_required": false,
                "topics": [],
                "visibility": "public",
                "forks": 0,
                "open_issues": 0,
                "watchers": 0,
                "default_branch": "main",
                "permissions": {
                    "admin": true,
                    "maintain": true,
                    "push": true,
                    "triage": true,
                    "pull": true
                }
            },
            {
                "id": 945056767,
                "node_id": "R_kgDOOFRr_w",
                "name": "pkg-fe-react-goblin-system",
                "full_name": "5h1ngy/pkg-fe-react-goblin-system",
                "private": false,
                "owner": {
                    "login": "5h1ngy",
                    "id": 109795840,
                    "node_id": "U_kgDOBotaAA",
                    "avatar_url": "https://avatars.githubusercontent.com/u/109795840?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/5h1ngy",
                    "html_url": "https://github.com/5h1ngy",
                    "followers_url": "https://api.github.com/users/5h1ngy/followers",
                    "following_url": "https://api.github.com/users/5h1ngy/following{/other_user}",
                    "gists_url": "https://api.github.com/users/5h1ngy/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/5h1ngy/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/5h1ngy/subscriptions",
                    "organizations_url": "https://api.github.com/users/5h1ngy/orgs",
                    "repos_url": "https://api.github.com/users/5h1ngy/repos",
                    "events_url": "https://api.github.com/users/5h1ngy/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/5h1ngy/received_events",
                    "type": "User",
                    "user_view_type": "public",
                    "site_admin": false
                },
                "html_url": "https://github.com/5h1ngy/pkg-fe-react-goblin-system",
                "description": "React UI component library",
                "fork": false,
                "url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system",
                "forks_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/forks",
                "keys_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/teams",
                "hooks_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/hooks",
                "issue_events_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/issues/events{/number}",
                "events_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/events",
                "assignees_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/assignees{/user}",
                "branches_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/branches{/branch}",
                "tags_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/tags",
                "blobs_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/languages",
                "stargazers_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/stargazers",
                "contributors_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/contributors",
                "subscribers_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/subscribers",
                "subscription_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/subscription",
                "commits_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/contents/{+path}",
                "compare_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/merges",
                "archive_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/downloads",
                "issues_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/issues{/number}",
                "pulls_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/labels{/name}",
                "releases_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/releases{/id}",
                "deployments_url": "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system/deployments",
                "created_at": "2025-03-08T15:01:36Z",
                "updated_at": "2025-03-08T15:08:16Z",
                "pushed_at": "2025-03-08T15:07:33Z",
                "git_url": "git://github.com/5h1ngy/pkg-fe-react-goblin-system.git",
                "ssh_url": "git@github.com:5h1ngy/pkg-fe-react-goblin-system.git",
                "clone_url": "https://github.com/5h1ngy/pkg-fe-react-goblin-system.git",
                "svn_url": "https://github.com/5h1ngy/pkg-fe-react-goblin-system",
                "homepage": "https://5h1ngy.github.io/pkg-fe-react-goblin-system",
                "size": 17676,
                "stargazers_count": 0,
                "watchers_count": 0,
                "language": "TypeScript",
                "has_issues": true,
                "has_projects": true,
                "has_downloads": true,
                "has_wiki": true,
                "has_pages": true,
                "has_discussions": false,
                "forks_count": 0,
                "mirror_url": null,
                "archived": false,
                "disabled": false,
                "open_issues_count": 0,
                "license": {
                    "key": "mit",
                    "name": "MIT License",
                    "spdx_id": "MIT",
                    "url": "https://api.github.com/licenses/mit",
                    "node_id": "MDc6TGljZW5zZTEz"
                },
                "allow_forking": true,
                "is_template": false,
                "web_commit_signoff_required": false,
                "topics": [
                    "chakra-ui",
                    "components",
                    "design-system",
                    "library",
                    "react",
                    "ui"
                ],
                "visibility": "public",
                "forks": 0,
                "open_issues": 0,
                "watchers": 0,
                "default_branch": "main",
                "permissions": {
                    "admin": true,
                    "maintain": true,
                    "push": true,
                    "triage": true,
                    "pull": true
                }
            }
        ]
    })
}, 1000))