import { GitHubRepo } from "./types"

export const getRepositoriesResponse = new Promise<{ data: (Record<string, any> & GitHubRepo<Record<string, any>>)[] }>(
    (resolve) =>
        setTimeout(() => {
            return resolve({
                data: [
                    // 1) FE
                    {
                        id: 945060412,
                        node_id: "R_kgDOOFR6PA",
                        name: "fe-react-portfolio",
                        html_url: "https://api.github.com/repos/5h1ngy/fe-react-portfolio",
                        updated_at: "2025-03-08T15:10:56Z",
                        license: null,
                        topics: [],
                        description: null,
                        homepage: "https://example.com/fe-react-portfolio",
                    },
                    {
                        // non appartiene a nessuna delle categorie previste (non ha prefisso fe-, cli-, be-, ecc.)
                        // ma lo manteniamo invariato
                        id: 945056767,
                        node_id: "R_kgDOOFRr_w",
                        name: "pkg-fe-react-goblin-system",
                        html_url: "https://api.github.com/repos/5h1ngy/pkg-fe-react-goblin-system",
                        updated_at: "2025-03-08T15:08:16Z",
                        license: {
                            name: "MIT License",
                        },
                        topics: ["chakra-ui", "components", "design-system", "library", "react", "ui"],
                        description: "React UI component library",
                        homepage: null,
                    },
                    // 2) Infrastructure (infra-) - rimane 1 solo repo
                    {
                        id: 123450001,
                        node_id: "R_kgDOG4A1FA",
                        name: "infra-terraform-lambda",
                        html_url: "https://api.github.com/repos/5h1ngy/infra-terraform-lambda",
                        updated_at: "2025-02-15T16:10:25Z",
                        license: {
                            name: "Apache License 2.0",
                        },
                        topics: ["terraform", "aws", "serverless", "infrastructure"],
                        description: "IaC setup for AWS Lambda functions using Terraform.",
                        homepage: "https://docs.example.com/infra-terraform-lambda",
                    },
                    // 3) CLI (cli-) - 5 repos totali
                    {
                        id: 123450002,
                        node_id: "R_kgDOG4A3GH",
                        name: "cli-smart-changelog",
                        html_url: "https://api.github.com/repos/5h1ngy/cli-smart-changelog",
                        updated_at: "2025-02-01T18:45:33Z",
                        license: {
                            name: "MIT License",
                        },
                        topics: ["cli", "changelog", "tooling"],
                        description: "A simple CLI tool to generate structured changelogs from your Git commit history.",
                        homepage: null,
                    },
                    {
                        id: 123450010,
                        node_id: "R_kgDOG4B10",
                        name: "cli-version-manager",
                        html_url: "https://api.github.com/repos/5h1ngy/cli-version-manager",
                        updated_at: "2025-03-05T10:20:00Z",
                        license: {
                            name: "MIT License",
                        },
                        topics: ["cli", "version", "manager"],
                        description: "CLI for managing project versions.",
                        homepage: "https://cli-tools.example.com/version-manager",
                    },
                    {
                        id: 123450011,
                        node_id: "R_kgDOG4B11",
                        name: "cli-deploy-tool",
                        html_url: "https://api.github.com/repos/5h1ngy/cli-deploy-tool",
                        updated_at: "2025-03-05T11:05:00Z",
                        license: null,
                        topics: ["cli", "deploy", "tool"],
                        description: "A straightforward CLI for deploying Node-based apps.",
                        homepage: null,
                    },
                    {
                        id: 123450012,
                        node_id: "R_kgDOG4B12",
                        name: "cli-auto-linter",
                        html_url: "https://api.github.com/repos/5h1ngy/cli-auto-linter",
                        updated_at: "2025-03-06T09:30:00Z",
                        license: {
                            name: "ISC",
                        },
                        topics: ["cli", "lint", "automation"],
                        description: "CLI that auto-lints your code.",
                        homepage: "https://auto-linter.example.com",
                    },
                    {
                        id: 123450013,
                        node_id: "R_kgDOG4B13",
                        name: "cli-build-buddy",
                        html_url: "https://api.github.com/repos/5h1ngy/cli-build-buddy",
                        updated_at: "2025-03-07T08:15:00Z",
                        license: null,
                        topics: ["cli", "build", "buddy"],
                        description: "Build buddy CLI for bundling and optimizing JS projects.",
                        homepage: null,
                    },
                    // 4) FE (fe-) - 5 repos totali
                    {
                        id: 123450003,
                        node_id: "R_kgDOG4A4IJ",
                        name: "fe-nextjs-landing",
                        html_url: "https://api.github.com/repos/5h1ngy/fe-nextjs-landing",
                        updated_at: "2025-02-28T11:15:45Z",
                        license: null,
                        topics: ["nextjs", "landing-page", "frontend"],
                        description: "Landing page starter built with Next.js and Chakra UI.",
                        homepage: "https://landing-pages.example.com/nextjs",
                    },
                    {
                        id: 123450014,
                        node_id: "R_kgDOG4B14",
                        name: "fe-vue-dashboard",
                        html_url: "https://api.github.com/repos/5h1ngy/fe-vue-dashboard",
                        updated_at: "2025-03-06T15:00:00Z",
                        license: null,
                        topics: ["vue", "dashboard", "frontend"],
                        description: "An admin dashboard built with Vue 3.",
                        homepage: null,
                    },
                    {
                        id: 123450015,
                        node_id: "R_kgDOG4B15",
                        name: "fe-svelte-playground",
                        html_url: "https://api.github.com/repos/5h1ngy/fe-svelte-playground",
                        updated_at: "2025-03-07T11:30:00Z",
                        license: {
                            name: "MIT License",
                        },
                        topics: ["svelte", "playground", "frontend"],
                        description: "A playground environment for exploring Svelte.",
                        homepage: "https://svelte-playground.example.com",
                    },
                    {
                        id: 123450016,
                        node_id: "R_kgDOG4B16",
                        name: "fe-react-admin",
                        html_url: "https://api.github.com/repos/5h1ngy/fe-react-admin",
                        updated_at: "2025-03-08T14:00:00Z",
                        license: null,
                        topics: ["react", "admin", "frontend"],
                        description: "React-based admin panel with Chakra UI.",
                        homepage: null,
                    },
                    // (Già presente “fe-react-portfolio” in cima)
                    // 5) BE (be-) - 5 repos totali
                    {
                        id: 123450004,
                        node_id: "R_kgDOG4A5KL",
                        name: "be-fastify-service",
                        html_url: "https://api.github.com/repos/5h1ngy/be-fastify-service",
                        updated_at: "2025-02-03T07:20:11Z",
                        license: null,
                        topics: ["fastify", "nodejs", "api", "backend"],
                        description: "Lightweight backend service built with Fastify and TypeScript.",
                        homepage: null,
                    },
                    {
                        id: 123450017,
                        node_id: "R_kgDOG4B17",
                        name: "be-nestjs-api",
                        html_url: "https://api.github.com/repos/5h1ngy/be-nestjs-api",
                        updated_at: "2025-03-05T17:00:00Z",
                        license: {
                            name: "MIT License",
                        },
                        topics: ["nestjs", "api", "backend"],
                        description: "Basic REST API built with NestJS.",
                        homepage: "https://nestjs.api.example.com",
                    },
                    {
                        id: 123450018,
                        node_id: "R_kgDOG4B18",
                        name: "be-hapi-server",
                        html_url: "https://api.github.com/repos/5h1ngy/be-hapi-server",
                        updated_at: "2025-03-06T09:50:00Z",
                        license: null,
                        topics: ["hapi", "nodejs", "backend"],
                        description: "Hapi.js server for modular microservices.",
                        homepage: null,
                    },
                    {
                        id: 123450019,
                        node_id: "R_kgDOG4B19",
                        name: "be-koa-auth",
                        html_url: "https://api.github.com/repos/5h1ngy/be-koa-auth",
                        updated_at: "2025-03-06T12:10:00Z",
                        license: null,
                        topics: ["koa", "authentication", "backend"],
                        description: "Koa-based authentication service.",
                        homepage: "https://koa-auth.example.com",
                    },
                    {
                        id: 123450020,
                        node_id: "R_kgDOG4B20",
                        name: "be-express-sample",
                        html_url: "https://api.github.com/repos/5h1ngy/be-express-sample",
                        updated_at: "2025-03-07T18:30:00Z",
                        license: {
                            name: "Apache License 2.0",
                        },
                        topics: ["express", "nodejs", "backend"],
                        description: "Express sample with TypeScript.",
                        homepage: null,
                    },
                    // 6) Videogames (fe-phaser) - 5 repos totali
                    {
                        id: 123450005,
                        node_id: "R_kgDOG4A6MN",
                        name: "fe-phaser-dungeon-crawler",
                        html_url: "https://api.github.com/repos/5h1ngy/fe-phaser-dungeon-crawler",
                        updated_at: "2025-03-02T10:40:00Z",
                        license: null,
                        topics: ["phaser", "2d-game", "videogame"],
                        description: "A 2D dungeon crawler built with Phaser.js.",
                        homepage: "https://games.example.com/dungeon-crawler",
                    },
                    {
                        id: 123450021,
                        node_id: "R_kgDOG4B21",
                        name: "fe-phaser-space-shooter",
                        html_url: "https://api.github.com/repos/5h1ngy/fe-phaser-space-shooter",
                        updated_at: "2025-03-07T10:20:00Z",
                        license: null,
                        topics: ["phaser", "space", "shooter"],
                        description: "A top-down space shooter with Phaser 3.",
                        homepage: null,
                    },
                    {
                        id: 123450022,
                        node_id: "R_kgDOG4B22",
                        name: "fe-phaser-platformer",
                        html_url: "https://api.github.com/repos/5h1ngy/fe-phaser-platformer",
                        updated_at: "2025-03-08T09:45:00Z",
                        license: null,
                        topics: ["phaser", "platformer", "videogame"],
                        description: "A platformer template built with Phaser 3.",
                        homepage: "https://games.example.com/platformer",
                    },
                    {
                        id: 123450023,
                        node_id: "R_kgDOG4B23",
                        name: "fe-phaser-arcade-racer",
                        html_url: "https://api.github.com/repos/5h1ngy/fe-phaser-arcade-racer",
                        updated_at: "2025-03-08T12:00:00Z",
                        license: {
                            name: "MIT License",
                        },
                        topics: ["phaser", "arcade", "racer"],
                        description: "Arcade racing game in Phaser.",
                        homepage: null,
                    },
                    {
                        id: 123450024,
                        node_id: "R_kgDOG4B24",
                        name: "fe-phaser-breakout",
                        html_url: "https://api.github.com/repos/5h1ngy/fe-phaser-breakout",
                        updated_at: "2025-03-09T14:15:00Z",
                        license: null,
                        topics: ["phaser", "breakout", "videogame"],
                        description: "Breakout clone using Phaser.",
                        homepage: "https://games.example.com/breakout",
                    },
                    // fs-* rimossi, come richiesto
                ],
            })
        }, 1000)
)
